### ISSUE TITLE
In DM's Anything in terminal crashes

### ISSUE THREAD

**Issue by 5731la** [Jan200101/Appu-cogs#6]
If I am not in a server (like a DM) it errors:
```
Ignoring exception in message
Traceback (most recent call last):
  File "/home/gido5731/.local/lib/python3.5/site-packages/discord/client.py", line 223, in _run_event
    yield from coro(*args, **kwargs)
  File "/home/gido5731/Discord-Selfbot/cogs/terminal.py", line 242, in on_message
    if (message.channel.id in self.sessions and self.enabled and message.author.id == message.guild.me.id): # DO NOT DELETE
AttributeError: 'NoneType' object has no attribute 'me'

```
after each message.

**Comment by appu1232** [comment]
Should be fixed with this commit
